spring:
  jackson:
    default-property-inclusion: non_null
  messages:
    basename: i18n/messages
  mvc:
    # Throw NoHandlerFoundException
    # See https://stackoverflow.com/questions/36733254/spring-boot-rest-how-to-configure-404-resource-not-found#36734193
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

feign:
  client:
    config:
      forecast:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

logging:
  level:
    # See https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/#feign-logging
    com.emeraldhieu.app.forecast.ForecastClient: DEBUG

server:
  error:
    include-message: always
    # Hide stack traces because spring-boot-dev-tools sets it automatically
    # See https://stackoverflow.com/questions/54827407/remove-trace-field-from-responsestatusexception#56546039
    include-stacktrace: never

application:
  forecast:
    # Configure API keys of multiple accounts here.
    apiKeys:
      - f598bbd03d2cd734a2c070aacf260467
      - f598bbd03d2cd734a2c070aacf260467
    retry:
      maxAttempts: 2
      maxDelay: 500
    cacheName: forecast
    cacheKeyPrefix: forecast
    timeToLiveInMinutes: 60
    maxIdleTimeInMinutes: 10
    apiKeyIndexCacheKey: apiKeyIndex
  redis:
    enabled: true
    servers:
      - redis://localhost:6379
    password: password
  api-rate-limit:
    cacheKey: apiRateLimit
    requestCount: 2
    durationInSeconds: 30
    expirationInSeconds: 30
  ip-rate-limit:
    namespace: ipRateLimit
    requestCount: 2
    durationInSeconds: 10
    expirationInSeconds: 60
